---
- hosts: all
  become: yes
  roles:
  - geerlingguy.java
  - idealista.tomcat-role 
  tasks:
  - name: copy war
    copy:
      scr: gameoflife.war
      dest: /opt/tomcat/webapps/gameoflife.war
    notify:
    - restart tomcat
handlers:
- name: restart tomcat
  service: tomcat
  satate: restarted
  enabled: yes